### ISSUE TITLE
Actions and table for 593

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#1248]
## Actions

see also project description at https://github.com/rism-digital/muscat/projects  
  

- [x] New layout in Muscat #1227
- [x] Adjust marc templates for holding (?)
- [x] Make maintenance script see https://github.com/rism-international/tasks/issues/967
- [x] Adjust Guidelines 
- [x] How to deal with multiple material layers?
- [x] Information for BSB about relevant changes
- [x] Adjust export if necessary
- [x] Subtags with composite template #1270 

## Table

see #1229, for holdings #1228

| 593$a Muscat 8 | Templates¹ | 593$a Muscat 9 | 593$b Muscat 9
| -------------- | -------------- | -------------- | ----------------
| Autograph manuscript | 1,2 | Autograph manuscript | Notated music | Notated music
| Possible autograph manuscript | 1,2 | Possible autograph manuscript | Notated music
| Partial autograph | 1,2 | Partial autograph | Notated music
| Manuscript copy | 1,2 | Manuscript copy | Notated music
| Manuscript copy with autograph annotations | 1,2 | Manuscript copy with autograph annotations | Notated music
| Libretto, handwritten | 4 | Manuscipt copy etc. | Libretto
| Treatise, handwritten | 6 | Manuscipt copy etc. | Treatise
| Print | 3,8 | Print | Notated music
| Print with autograph annotations | 3,8 | Print with autograph annotations | Notated music
| Print with non-autograph annotations | 3,8 | Print with non-autograph annotations | Notated music
| Libretto, printed | 5, 9 | Print etc. | Libretto
| Treatise, printed | 7, 10 | Print etc. | Treatise
| Composite (#1270) | 11 | Composite | Mixed
| Other | 0 | Other | Other
| (Print)³ | Holding | Print | Notated music
| Print with autograph annotations | Holding | Print with autograph annotations | Notated music
| Print with non-autograph annotations | Holding | Print with non-autograph annotations | Notated music
| Additional manuscript material | Holding | Additional manuscript material | Notated music

¹ see https://github.com/rism-digital/muscat/blob/c7ac771e34398a2e88bfa9435e0354e9910c9edf/lib/marc_source.rb#L4-L17
